wandb_version: 1

learning_rate:
  desc: null
  value: 2.0e-05
n_epoch:
  desc: null
  value: 15
batch_size:
  desc: null
  value: 8
_wandb:
  desc: null
  value:
    python_version: 3.10.7
    cli_version: 0.15.0
    framework: huggingface
    huggingface_version: 4.22.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1682399933.361838
    t:
      1:
      - 1
      - 5
      - 11
      - 49
      - 51
      - 53
      - 55
      - 71
      2:
      - 1
      - 5
      - 11
      - 49
      - 51
      - 53
      - 55
      - 71
      3:
      - 16
      - 23
      4: 3.10.7
      5: 0.15.0
      6: 4.22.2
      8:
      - 4
      - 5
